--- !ditz.rubyforge.org,2008-03-06/project 
name: Wink
version: "0.2"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: wink
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :released
  release_time: 2008-05-23 18:44:19.780210 Z
  log_events: 
  - - 2008-05-22 18:25:52.791085 Z
    - Ryan Tomayko <r@tomayko.com>
    - created
    - ""
  - - 2008-05-23 18:44:19.780264 Z
    - Ryan Tomayko <r@tomayko.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.2"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-05-25 15:38:11.731275 Z
    - Ryan Tomayko <r@tomayko.com>
    - created
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.3"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-05-25 19:56:16.096385 Z
    - Ryan Tomayko <r@tomayko.com>
    - created
    - ""
